### ISSUE TITLE
PersistenceEntityTests

### ISSUE THREAD

**Issue by gavinking** [jakartaredhat/hibernate-data-tck#13]
`PersistenceEntityTests` fails with errors like:

```
[ERROR] org.hibernate.ee.jakarta.data.tck.StandalonePersistenceEntityTests.testEntityManager -- Time elapsed: 2.837 s <<< ERROR!
jakarta.data.exceptions.DataException: UnknownParameterException(`Product.versionNum` for RESTRICT - UPDATE : e.j.t.d.s.p.Product)
        at ee.jakarta.tck.data.standalone.persistence.Catalog_.save(Catalog_.java:324)
        at ee.jakarta.tck.data.standalone.persistence.Catalog_$Proxy$_$$_WeldClientProxy.save(Unknown Source)
        at ee.jakarta.tck.data.standalone.persistence.PersistenceEntityTests.testEntityManager(PersistenceEntityTests.java:65)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
 ```

This is due to a bug in Hibernate core. (The `@Incubating` method `StatelessSession.upsert()` does not yet correctly handle versioned entities.)

See https://hibernate.atlassian.net/browse/HHH-17934.

**Comment by gavinking** [comment]
Fixed well enough for now by #16.
